# **PREPROCESSING NOTEBOOK**

## Libraries

In [2]:
import pandas as pd

## Load Data

In [11]:
data = pd.read_csv('../customer_info.csv',index_col=0)
data.head()

,customer_id,customer_name,customer_gender,customer_birthdate,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,...,lifetime_spend_fish,lifetime_spend_hygiene,lifetime_spend_videogames,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number,latitude,longitude
0,29930,April Clark,female,01/15/1972 02:27 PM,2.0,2.0,1.0,4.0,7789.0,5601.0,...,1894.0,457.0,412.0,428.0,386.0,0.158741,2018.0,NaN,38.721807,-9.125534
1,6813,Bsc. Paul Ketchum,male,07/31/1944 10:53 AM,0.0,1.0,0.0,4.0,8653.0,35.0,...,346.0,394.0,75.0,226.0,73.0,1.227890,2013.0,971840.0,38.734668,-9.163533
2,39451,Mary Downing,female,11/13/1989 02:11 PM,2.0,3.0,0.0,7.0,15605.0,4275.0,...,1971.0,920.0,335.0,192.0,319.0,0.101598,2011.0,NaN,38.787126,-9.147077
3,21557,Manuel Kueny,male,08/09/1976 06:23 AM,0.0,0.0,1.0,1.0,13440.0,16366.0,...,785.0,139.0,679.0,270.0,221.0,0.259943,2009.0,NaN,38.741816,-9.159700
4,16415,Phd. Curtis Tharp,male,07/11/1966 08:12 AM,1.0,1.0,1.0,5.0,49250.0,3197.0,...,1492.0,1046.0,112.0,144.0,244.0,0.317822,2012.0,925367.0,38.785921,-9.149221

In [8]:
customer_info = pd.read_csv('D:\OneDrive - NOVAIMS\Year 2\S4\Machine Learning ll\Project\ML2_Group9\customer_info.csv', index_col=0)
customer_info.head()

,customer_id,customer_name,customer_gender,customer_birthdate,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,...,lifetime_spend_fish,lifetime_spend_hygiene,lifetime_spend_videogames,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number,latitude,longitude
0,29930,April Clark,female,01/15/1972 02:27 PM,2.0,2.0,1.0,4.0,7789.0,5601.0,...,1894.0,457.0,412.0,428.0,386.0,0.158741,2018.0,NaN,38.721807,-9.125534
1,6813,Bsc. Paul Ketchum,male,07/31/1944 10:53 AM,0.0,1.0,0.0,4.0,8653.0,35.0,...,346.0,394.0,75.0,226.0,73.0,1.227890,2013.0,971840.0,38.734668,-9.163533
2,39451,Mary Downing,female,11/13/1989 02:11 PM,2.0,3.0,0.0,7.0,15605.0,4275.0,...,1971.0,920.0,335.0,192.0,319.0,0.101598,2011.0,NaN,38.787126,-9.147077
3,21557,Manuel Kueny,male,08/09/1976 06:23 AM,0.0,0.0,1.0,1.0,13440.0,16366.0,...,785.0,139.0,679.0,270.0,221.0,0.259943,2009.0,NaN,38.741816,-9.159700
4,16415,Phd. Curtis Tharp,male,07/11/1966 08:12 AM,1.0,1.0,1.0,5.0,49250.0,3197.0,...,1492.0,1046.0,112.0,144.0,244.0,0.317822,2012.0,925367.0,38.785921,-9.149221

In [14]:
data1 = pd.read_csv('../customer_basket.csv')
data1

,invoice_id,list_of_goods,customer_id
0,5062209,"['megaman zero 3', 'energy bar', 'pokemon viol...",4925
1,4272512,"['black beer', 'bramble', 'laptop', 'pokemon v...",19046
2,7121052,"['soup', 'shallot', 'cake', 'fresh bread', 'cr...",10318
3,5847748,"['soup', 'cooking oil', 'cereals', 'oil', 'dog...",27283
4,6336114,"['eggplant', 'mint green tea', 'oil', 'bacon',...",16072
...,...,...,...
99995,5389466,"['frozen smoothie', 'avocado', 'dog food', 'ch...",26170
99996,10387390,"['cake', 'antioxydant juice', 'honey', 'toothp...",19691
99997,7103407,"['candy bars', 'spaghetti', 'oil', 'final fant...",1720
99998,4093515,"['shallot', 'cereals', 'oil', 'deodorant', 'me...",24989
99999,6611217,"['soup', 'napkins', 'pokemon violet', 'ratchet...",482

In [12]:
customer_basket = pd.read_csv('D:\OneDrive - NOVAIMS\Year 2\S4\Machine Learning ll\Project\ML2_Group9\customer_basket.csv', sep=',')
customer_basket.head()

   invoice_id                                      list_of_goods  customer_id
0     5062209  ['megaman zero 3', 'energy bar', 'pokemon viol...         4925
1     4272512  ['black beer', 'bramble', 'laptop', 'pokemon v...        19046
2     7121052  ['soup', 'shallot', 'cake', 'fresh bread', 'cr...        10318
3     5847748  ['soup', 'cooking oil', 'cereals', 'oil', 'dog...        27283
4     6336114  ['eggplant', 'mint green tea', 'oil', 'bacon',...        16072

## _Customer Info_

### 1. Duplicates

In [ ]:
# Exploration

In [ ]:
# Treatment

### 2. Outliers

In [ ]:
# Exploration

In [ ]:
# Treatment

### 3. Missing Values

In [ ]:
# Exploration

In [ ]:
# Treatment

### 4. Encoding

In [ ]:
# Exploration

In [ ]:
# Treatment

### 5. Inconsistencies

In [ ]:
# Exploration

In [ ]:
# Treatment

### 6. Scalling

In [ ]:
# Exploration

In [ ]:
# Treatment

### 7. Redundancy

In [ ]:
# Exploration

In [ ]:
# Treatment

## _Customer Basket_

### 1. Duplicates

In [ ]:
# Exploration

In [ ]:
# Treatment

### 2. Outliers

In [ ]:
# Exploration

In [ ]:
# Treatment

### 3. Missing Values

In [ ]:
# Exploration

In [ ]:
# Treatment

### 4. Encoding

In [ ]:
# Exploration

In [ ]:
# Treatment

### 5. Inconsistencies

In [ ]:
# Exploration

In [ ]:
# Treatment

### 6. Scalling

In [ ]:
# Exploration

In [ ]:
# Treatment

### 7. Redundancy

In [ ]:
# Exploration

In [ ]:
# Treatment