# **PREPROCESSING NOTEBOOK**

## Libraries

In [17]:
import pandas as pd
import seaborn as sns
#hello

## Load Data

In [3]:
customer_info = pd.read_csv('../customer_info.csv',index_col=0)
customer_info.head()

,customer_id,customer_name,customer_gender,customer_birthdate,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,...,lifetime_spend_fish,lifetime_spend_hygiene,lifetime_spend_videogames,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number,latitude,longitude
0,29930,April Clark,female,01/15/1972 02:27 PM,2.0,2.0,1.0,4.0,7789.0,5601.0,...,1894.0,457.0,412.0,428.0,386.0,0.158741,2018.0,NaN,38.721807,-9.125534
1,6813,Bsc. Paul Ketchum,male,07/31/1944 10:53 AM,0.0,1.0,0.0,4.0,8653.0,35.0,...,346.0,394.0,75.0,226.0,73.0,1.227890,2013.0,971840.0,38.734668,-9.163533
2,39451,Mary Downing,female,11/13/1989 02:11 PM,2.0,3.0,0.0,7.0,15605.0,4275.0,...,1971.0,920.0,335.0,192.0,319.0,0.101598,2011.0,NaN,38.787126,-9.147077
3,21557,Manuel Kueny,male,08/09/1976 06:23 AM,0.0,0.0,1.0,1.0,13440.0,16366.0,...,785.0,139.0,679.0,270.0,221.0,0.259943,2009.0,NaN,38.741816,-9.159700
4,16415,Phd. Curtis Tharp,male,07/11/1966 08:12 AM,1.0,1.0,1.0,5.0,49250.0,3197.0,...,1492.0,1046.0,112.0,144.0,244.0,0.317822,2012.0,925367.0,38.785921,-9.149221

In [4]:
customer_basket = pd.read_csv('../customer_basket.csv')
customer_basket.head()

   invoice_id                                      list_of_goods  customer_id
0     5062209  ['megaman zero 3', 'energy bar', 'pokemon viol...         4925
1     4272512  ['black beer', 'bramble', 'laptop', 'pokemon v...        19046
2     7121052  ['soup', 'shallot', 'cake', 'fresh bread', 'cr...        10318
3     5847748  ['soup', 'cooking oil', 'cereals', 'oil', 'dog...        27283
4     6336114  ['eggplant', 'mint green tea', 'oil', 'bacon',...        16072

## _Customer Info_

In [5]:
print(f'customer_info shape: {customer_info.shape}')

customer_info shape: (34060, 25)

In [6]:
print(f'customer_info main metrics: \n')
customer_info.describe().T

customer_info main metrics:

,count,mean,std,min,25%,50%,75%,max
customer_id,34060.0,20010.854433,11557.889072,1.000000,10018.750000,19985.500000,30042.250000,40000.000000
kids_home,33311.0,1.170244,1.307319,0.000000,0.000000,1.000000,1.000000,10.000000
teens_home,33277.0,0.936292,0.759579,0.000000,0.000000,1.000000,1.000000,4.000000
number_complaints,33038.0,0.832042,0.771205,0.000000,0.000000,1.000000,1.000000,4.000000
distinct_stores_visited,33379.0,2.914078,1.549081,1.000000,2.000000,3.000000,4.000000,10.000000
lifetime_spend_groceries,34060.0,22818.404698,20098.763199,0.000000,9346.000000,15877.500000,30428.250000,158544.000000
lifetime_spend_electronics,34060.0,3816.022343,3858.352640,0.000000,860.000000,2958.000000,5309.000000,37523.000000
typical_hour,32698.0,13.200746,4.681384,6.000000,9.000000,13.000000,16.000000,24.000000
lifetime_spend_vegetables,33038.0,738.642079,679.599323,0.000000,222.000000,451.000000,1089.750000,5380.000000
lifetime_spend_nonalcohol_drinks,34060.0,478.382854,282.132536,0.000000,231.000000,453.000000,661.000000,1702.000000
lifetime_spend_alcohol_drinks,33379.0,838.482998,596.518224,1.000000,347.000000,705.000000,1299.000000,4907.000000
lifetime_spend_meat,34060.0,916.211274,534.330738,0.000000,578.000000,916.000000,1257.000000,3040.000000
lifetime_spend_fish,32357.0,828.842662,655.803300,0.000000,269.000000,714.000000,1269.000000,4043.000000
lifetime_spend_hygiene,34060.0,711.297534,481.230522,0.000000,338.000000,634.000000,1001.000000,3286.000000
lifetime_spend_videogames,34060.0,399.434968,320.221650,0.000000,185.000000,319.000000,506.000000,2176.000000
lifetime_spend_petfood,34060.0,317.755843,150.513835,0.000000,212.000000,313.000000,414.000000,1007.000000
lifetime_total_distinct_products,34060.0,156.691339,118.969652,0.000000,62.000000,122.000000,235.000000,946.000000
percentage_of_products_bought_promotion,34060.0,0.337093,0.322766,-1.340710,0.113353,0.240373,0.514691,1.952971
year_first_transaction,34060.0,2014.593218,4.739037,1995.000000,2011.000000,2015.000000,2018.000000,2026.000000
loyalty_card_number,23152.0,950528.738856,28904.951217,900009.000000,925548.500000,950704.000000,975600.250000,999996.000000
latitude,34060.0,38.747812,0.021562,38.700486,38.730512,38.747755,38.764967,38.793672
longitude,34060.0,-9.156987,0.024561,-9.214894,-9.175987,-9.157015,-9.140522,-9.065429

### 1. Duplicates

In [8]:
# Exploration

In [ ]:
# Treatment

### 2. Outliers

In [ ]:
# Exploration

In [ ]:
# Treatment

### 3. Missing Values

In [9]:
# Exploration
customer_info.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34060 entries, 0 to 34059
Data columns (total 25 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   customer_id                              34060 non-null  int64
 1   customer_name                            34060 non-null  object
 2   customer_gender                          34060 non-null  object
 3   customer_birthdate                       33719 non-null  object
 4   kids_home                                33311 non-null  float64
 5   teens_home                               33277 non-null  float64
 6   number_complaints                        33038 non-null  float64
 7   distinct_stores_visited                  33379 non-null  float64
 8   lifetime_spend_groceries                 34060 non-null  float64
 9   lifetime_spend_electronics               34060 non-null  float64
 10  typical_hour                             32698 non-null  float64
 11  lifetime_spend_vegetables                33038 non-null  float64
 12  lifetime_spend_nonalcohol_drinks         34060 non-null  float64
 13  lifetime_spend_alcohol_drinks            33379 non-null  float64
 14  lifetime_spend_meat                      34060 non-null  float64
 15  lifetime_spend_fish                      32357 non-null  float64
 16  lifetime_spend_hygiene                   34060 non-null  float64
 17  lifetime_spend_videogames                34060 non-null  float64
 18  lifetime_spend_petfood                   34060 non-null  float64
 19  lifetime_total_distinct_products         34060 non-null  float64
 20  percentage_of_products_bought_promotion  34060 non-null  float64
 21  year_first_transaction                   34060 non-null  float64
 22  loyalty_card_number                      23152 non-null  float64
 23  latitude                                 34060 non-null  float64
 24  longitude                                34060 non-null  float64
dtypes: float64(21), int64(1), object(3)
memory usage: 6.8+ MB

In [14]:
customer_info.describe().T

,count,mean,std,min,25%,50%,75%,max
customer_id,34060.0,20010.854433,11557.889072,1.000000,10018.750000,19985.500000,30042.250000,40000.000000
kids_home,33311.0,1.170244,1.307319,0.000000,0.000000,1.000000,1.000000,10.000000
teens_home,33277.0,0.936292,0.759579,0.000000,0.000000,1.000000,1.000000,4.000000
number_complaints,33038.0,0.832042,0.771205,0.000000,0.000000,1.000000,1.000000,4.000000
distinct_stores_visited,33379.0,2.914078,1.549081,1.000000,2.000000,3.000000,4.000000,10.000000
lifetime_spend_groceries,34060.0,22818.404698,20098.763199,0.000000,9346.000000,15877.500000,30428.250000,158544.000000
lifetime_spend_electronics,34060.0,3816.022343,3858.352640,0.000000,860.000000,2958.000000,5309.000000,37523.000000
typical_hour,32698.0,13.200746,4.681384,6.000000,9.000000,13.000000,16.000000,24.000000
lifetime_spend_vegetables,33038.0,738.642079,679.599323,0.000000,222.000000,451.000000,1089.750000,5380.000000
lifetime_spend_nonalcohol_drinks,34060.0,478.382854,282.132536,0.000000,231.000000,453.000000,661.000000,1702.000000
lifetime_spend_alcohol_drinks,33379.0,838.482998,596.518224,1.000000,347.000000,705.000000,1299.000000,4907.000000
lifetime_spend_meat,34060.0,916.211274,534.330738,0.000000,578.000000,916.000000,1257.000000,3040.000000
lifetime_spend_fish,32357.0,828.842662,655.803300,0.000000,269.000000,714.000000,1269.000000,4043.000000
lifetime_spend_hygiene,34060.0,711.297534,481.230522,0.000000,338.000000,634.000000,1001.000000,3286.000000
lifetime_spend_videogames,34060.0,399.434968,320.221650,0.000000,185.000000,319.000000,506.000000,2176.000000
lifetime_spend_petfood,34060.0,317.755843,150.513835,0.000000,212.000000,313.000000,414.000000,1007.000000
lifetime_total_distinct_products,34060.0,156.691339,118.969652,0.000000,62.000000,122.000000,235.000000,946.000000
percentage_of_products_bought_promotion,34060.0,0.337093,0.322766,-1.340710,0.113353,0.240373,0.514691,1.952971
year_first_transaction,34060.0,2014.593218,4.739037,1995.000000,2011.000000,2015.000000,2018.000000,2026.000000
loyalty_card_number,23152.0,950528.738856,28904.951217,900009.000000,925548.500000,950704.000000,975600.250000,999996.000000
latitude,34060.0,38.747812,0.021562,38.700486,38.730512,38.747755,38.764967,38.793672
longitude,34060.0,-9.156987,0.024561,-9.214894,-9.175987,-9.157015,-9.140522,-9.065429

In [14]:
# Treatment
customer_info.isnull().sum()

customer_id                                    0
customer_name                                  0
customer_gender                                0
customer_birthdate                           341
kids_home                                    749
teens_home                                   783
number_complaints                           1022
distinct_stores_visited                      681
lifetime_spend_groceries                       0
lifetime_spend_electronics                     0
typical_hour                                1362
lifetime_spend_vegetables                   1022
lifetime_spend_nonalcohol_drinks               0
lifetime_spend_alcohol_drinks                681
lifetime_spend_meat                            0
lifetime_spend_fish                         1703
lifetime_spend_hygiene                         0
lifetime_spend_videogames                      0
lifetime_spend_petfood                         0
lifetime_total_distinct_products               0
percentage_of_products_bought_promotion        0
year_first_transaction                         0
loyalty_card_number                        10908
latitude                                       0
longitude                                      0
dtype: int64

In [ ]:
#cannot impute for customer_birthdate and loylty_card_number

In [10]:
customer_info[customer_info.isna().sum(axis=1) == 4]

,customer_id,customer_name,customer_gender,customer_birthdate,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,...,lifetime_spend_fish,lifetime_spend_hygiene,lifetime_spend_videogames,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number,latitude,longitude
407,31921,Diana Morales,female,05/22/1960 09:12 AM,1.0,1.0,NaN,NaN,18181.0,3071.0,...,NaN,577.0,221.0,184.0,63.0,0.018141,2013.0,NaN,38.786738,-9.182725
4686,29510,Betty Phillips,female,11/01/1988 05:42 AM,1.0,NaN,1.0,3.0,11689.0,1779.0,...,NaN,509.0,185.0,290.0,113.0,0.079789,2014.0,NaN,38.719544,-9.162084
4973,34051,Martin Barnett,male,04/08/1993 03:50 PM,2.0,2.0,2.0,2.0,7619.0,974.0,...,NaN,175.0,76.0,176.0,84.0,1.077490,2019.0,NaN,38.747157,-9.156142
5045,17260,Leslie Williams,female,11/28/1994 02:48 AM,2.0,0.0,2.0,NaN,8306.0,589.0,...,NaN,583.0,180.0,173.0,67.0,0.349916,2019.0,NaN,38.747036,-9.156917
10937,39771,Stephanie Flurry,female,04/17/1945 12:31 AM,NaN,1.0,0.0,3.0,25564.0,7889.0,...,787.0,1933.0,573.0,293.0,152.0,0.145950,2015.0,NaN,38.752346,-9.073041
13963,32806,Christopher Lomanto,male,11/02/1962 10:41 PM,1.0,NaN,1.0,2.0,8751.0,1941.0,...,126.0,1151.0,214.0,254.0,66.0,0.132375,2015.0,NaN,38.729379,-9.147951
14001,38413,Gordon Gullo,male,04/11/1999 02:19 PM,1.0,0.0,NaN,2.0,56532.0,1652.0,...,519.0,1899.0,431.0,330.0,114.0,0.442048,2019.0,NaN,38.760468,-9.193747
14040,27984,Barbara Sisco,female,04/27/1943 04:55 PM,4.0,2.0,0.0,NaN,24283.0,5905.0,...,2121.0,311.0,293.0,328.0,345.0,0.212184,2013.0,NaN,38.747933,-9.126635
14047,32304,William Williams,male,NaN,0.0,NaN,1.0,2.0,35008.0,12116.0,...,1376.0,241.0,1786.0,369.0,43.0,0.255800,2020.0,NaN,38.742286,-9.156888
15402,26623,Brenda Perez,female,02/28/2000 01:09 AM,1.0,0.0,0.0,NaN,56182.0,14218.0,...,NaN,1342.0,581.0,497.0,466.0,0.632051,2024.0,NaN,38.728673,-9.166530
15447,21073,Lisa Young,female,04/13/1996 12:48 AM,2.0,1.0,NaN,NaN,6551.0,567.0,...,241.0,108.0,137.0,149.0,87.0,-0.074373,2020.0,NaN,38.747708,-9.155993
17450,36816,Troy Compos,male,01/17/1954 05:08 PM,0.0,NaN,1.0,NaN,26209.0,18050.0,...,286.0,146.0,635.0,596.0,220.0,0.392715,2015.0,NaN,38.769719,-9.162354
19255,38051,Harold Wilkerson,male,08/17/1944 10:31 AM,NaN,1.0,1.0,1.0,17210.0,3297.0,...,NaN,561.0,179.0,178.0,82.0,0.025013,2018.0,NaN,38.752740,-9.163937
21271,33979,Sue Satchell,female,06/15/1953 03:55 AM,3.0,2.0,1.0,NaN,16729.0,6257.0,...,NaN,1245.0,378.0,122.0,229.0,0.155342,2001.0,NaN,38.747414,-9.147510
21557,1674,John Chu,male,04/30/1997 12:12 AM,NaN,0.0,2.0,NaN,88589.0,124.0,...,NaN,236.0,214.0,406.0,148.0,0.139663,2021.0,NaN,38.723336,-9.214069
22722,36903,Miguel Stokes,male,03/15/1944 12:24 AM,NaN,1.0,3.0,2.0,11409.0,923.0,...,954.0,310.0,34.0,346.0,173.0,0.487541,2016.0,NaN,38.785444,-9.140751
28665,16751,Brenda Ruiz,female,06/30/1990 12:33 AM,2.0,1.0,2.0,NaN,9232.0,351.0,...,NaN,73.0,107.0,176.0,20.0,-0.141172,2016.0,NaN,38.748410,-9.156786

### 4. Encoding

In [12]:
customer_info.select_dtypes(include = object)

           customer_name customer_gender   customer_birthdate
0            April Clark          female  01/15/1972 02:27 PM
1      Bsc. Paul Ketchum            male  07/31/1944 10:53 AM
2           Mary Downing          female  11/13/1989 02:11 PM
3           Manuel Kueny            male  08/09/1976 06:23 AM
4      Phd. Curtis Tharp            male  07/11/1966 08:12 AM
...                  ...             ...                  ...
34055          Mary Diaz          female  01/20/1999 06:47 PM
34056         John Gross            male  08/01/1984 07:50 PM
34057    Kathleen Harper          female  09/16/2000 07:22 AM
34058  Msc. Jenny Landry          female  04/09/1961 10:52 AM
34059        Roy Wilkins            male  03/25/1993 09:59 PM

[34060 rows x 3 columns]

In [16]:
customer_info.describe(include = object)

       customer_name customer_gender   customer_birthdate
count          34060           34060                33719
unique         33579               2                33710
top     Robert Brown            male  12/23/1956 11:57 PM
freq               6           17133                    2

In [ ]:
# Exploration

In [ ]:
# Treatment

### 5. Inconsistencies

In [ ]:
# Exploration

In [ ]:
# Treatment

### 6. Scalling

In [ ]:
# Exploration

In [ ]:
# Treatment

### 7. Redundancy

In [ ]:
# Exploration

In [ ]:
# Treatment

## _Customer Basket_

### 1. Duplicates

In [ ]:
# Exploration

In [ ]:
# Treatment

### 2. Outliers

In [ ]:
# Exploration

In [ ]:
# Treatment

### 3. Missing Values

In [12]:
# Exploration

In [13]:
# Treatment

### 4. Encoding

In [ ]:
# Exploration

In [ ]:
# Treatment

### 5. Inconsistencies

In [ ]:
# Exploration

In [ ]:
# Treatment

### 6. Scalling

In [ ]:
# Exploration

In [ ]:
# Treatment

### 7. Redundancy

In [ ]:
# Exploration

In [ ]:
# Treatment